window._externalContentHash="Zzh5YTNtZjBpZGM1djI2NzdlNGdqaDlxZ2I4aHYyMmp4NDE3cHllcWR1eWFxcWRtdnJueHhkMTh5aXJ4NDc5MDBkdDE4bW1kcDFucnEweGt3";
window.bkLinkData={
  "Frequently Used:":"divider",
  "SDZ (Via D-Cloud)":{"auth":"yes","dest":"http://goo.gl/er3imb"},
  "SDZ Citrix":{"auth":"yes","dest":"http://goo.gl/mTG7jl"},
  "Hyderabad Citrix":{"auth":"yes","dest":"http://goo.gl/PcjbII"},
  "VZWeb Home":{"auth":"yes","dest":"http://goo.gl/udPlbw"},
  "VDSI Web Home":{"auth":"yes","dest":"http://goo.gl/fRPnKq"},
  "Pace":{"auth":"yes","dest":"http://goo.gl/gGRg7e"},
  "Holidays":{"auth":"yes","dest":"http://goo.gl/13q9Se"},
  "VZ Learn":{"auth":"yes","dest":"http://goo.gl/3IfhzB"},
  "Talent Development Portal":{"auth":"yes","dest":"http://goo.gl/BvLOqQ"},
  /*"Quality Center (QC-ALM)":{"auth":"yes","dest":"http://goo.gl/Ghk4EE"},*/
  "Quality Center (QC-ALM)":{"auth":"yes","dest":"https://goo.gl/g706eG"},
  "SiteCatalyst Reports":"http://goo.gl/nhEv2V",
  "Leave Management System (LMS)":{"auth":"yes","dest":"http://goo.gl/oFoF11"},
  "HR Live":{"auth":"yes","dest":"http://goo.gl/T8wPZN"},
  "Verizon Helpdesk Portal":{"auth":"yes","dest":"http://goo.gl/kJOMZX"},
  "VZ About You":{"auth":"yes","dest":"http://goo.gl/RSu02T"},
  "VZ Work Tools":{"auth":"yes","dest":"http://goo.gl/2o67P6"},
  "VZ Brand Central":"https://goo.gl/yVOGcq",
  "D-Cloud TPA":{"auth":"yes","dest":"http://goo.gl/ml3NTg"},
  "UI Team Assignments":"divider",
  "UI Team Resource Assignments":{"auth":"yes","dest":"http://goo.gl/jGZQ1R"},
  "Market Analysis":"divider",
  "Verizon / AT & T / Sprint / T-Mobile":"http://goo.gl/qxI7E5",
  "Important Links:":"divider",
  "Verizon Payroll":"http://goo.gl/obbGBT",
  "Useful Links":{"auth":"yes","dest":"http://goo.gl/Z5frPl"},
  "ESP Wiki":{"auth":"yes","dest":"http://goo.gl/XOlH2s"},
  "***** ATG Dev Environment *****":"http://goo.gl/2OjVI5",
  "ATG - BCC Env Mapping":{"auth":"yes","dest":"http://goo.gl/dAq6Cu"},
  "GSS Environment Links":{"auth":"yes","dest":"http://goo.gl/VEcxV2"},
  "RESET NON-PROD PW 1":{"auth":"yes","dest":"http://goo.gl/CdYb2M"},
  "RESET NON-PROD PW 2":{"auth":"yes","dest":"http://goo.gl/Tb8pBl"},
  "Software Central (VZDelivery)":{"auth":"yes","dest":"http://goo.gl/eR1Sm8"},
  "LDS India":{"auth":"yes","dest":"http://goo.gl/AvnCCR"},
  "Sharepoint eCommerce VDSI":{"auth":"yes","dest":"http://goo.gl/Y0lUeV"},
  "ESP Sharepoint":{"auth":"yes","dest":"http://goo.gl/AeXC83"},
  "ESP Shared Documents VDSI":{"auth":"yes","dest":"http://goo.gl/qeYV9H"},
  "VZ Printer Configuration":{"auth":"yes","dest":"http://goo.gl/qX4jk0"},
  "VZ PF Portal":{"auth":"yes","dest":"http://goo.gl/0g8lYF"},
  "Sametime 9 WebClient":{"auth":"yes","dest":"http://goo.gl/GZRrEj"},
  "Reset SDZ Password":{"auth":"yes","dest":"http://goo.gl/yANAfz"},
  "VZ Distro Management":{"auth":"yes","dest":"http://goo.gl/cRrBaV"},
  "Evault User Stats":{"auth":"yes","dest":"http://goo.gl/qVKObH"},
  "Test Environments:":"divider",
  "QA1":{"auth":"yes","dest":"http://goo.gl/Ot8NpB"},
  "QA5":{"auth":"yes","dest":"http://goo.gl/BwfBa1"},
  "Pre-Test":{"auth":"yes","dest":"http://goo.gl/JEFOzJ"},
  "Testman":{"auth":"yes","dest":"http://goo.gl/xKf90U"},
  "PROD Datacenter Switch":"divider",
  "SDC":"http://goo.gl/QAdnu7",
  "TDC":"http://goo.gl/pDQFlG",
  "ODC":"http://goo.gl/HQd58P",
  /*
  "Hidden Links:":"divider",
  "BC-License":{"auth":"yes","dest":"http://goo.gl/WhIo08"},
  "JRebel New":{"auth":"yes","dest":"http://goo.gl/RJ4Emc"},
  "JRebel":{"auth":"yes","dest":"http://goo.gl/5XLZFx"},
  "VZProxy":{"auth":"yes","dest":"http://goo.gl/gbGLWa"},
  "Utilities":{"auth":"yes","dest":"https://goo.gl/SjbYMG","sharevia":"kcak121.phoenix"},
  "CurryURL":{"auth":"yes","dest":"http://goo.gl/MakisC"},
  "VZW-WEBEX":{"auth":"yes","dest":"https://goo.gl/10BkXx"},
  */
  "Web Search:":"divider",
  "Google Search":"http://www.google.com",
  "Wikipedia":"http://goo.gl/tV3t1U",
  "Stackoverflow.com":"http://goo.gl/SFvnPE",
  "Utilities:":"divider",
  "\"English\" Dictionary":"http://goo.gl/teqidm",
  "Translate (Google)":"http://goo.gl/7YBg5G",
  "Transliterate (Google)":"http://goo.gl/Q3ztlp",
  "eCommerce:":"divider",
  "Verizon Wireless":"http://goo.gl/osrmco",
  "Flipkart":"http://goo.gl/m5tVCn",
  " ":"divider"
};
window.executeNow();
